#pragma once

namespace Client
{
	enum LEVELID { LEVEL_STATIC, LEVEL_IMGUI, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_LOADING, LEVEL_END };

	enum CLINT_ANIM
	{
		CLINT_SHOOT = 5,
		CLINT_DASH = 27,
		CLINT_IDLE = 64,
		CLINT_MVP = 74,
		CLINT_RUN = 89,
		CLINT_SKILL_01 = 109,
		CLINT_SKILL_02 = 112,
		CLINT_ULTIMATE01 = 133,
		CLINT_ULTIMATE02 = 135,
		CLINT_WALK_B = 142,
		CLINT_WALK_BL,
		CLINT_WALK_BL_45,
		CLINT_WALK_BR,
		CLINT_WALK_BR_45,
		CLINT_WALK_F,
		CLINT_WALK_FL,
		CLINT_WALK_FL_45,
		CLINT_WALK_FR,
		CLINT_WALK_FR_45,
		CLINT_WEAPONCHHANGE = 152,
	};

	enum ALIEN_PRAWN_ANIM
	{
		ALIEN_PRAWN_APPEAR,
		ALIEN_PRAWN_ATTACK01,
		ALIEN_PRAWN_ATTACK01_MID,
		ALIEN_PRAWN_ATTACK02,
		ALIEN_PRAWN_CHARGE,
		ALIEN_PRAWN_CHARGE_IN,
		ALIEN_PRAWN_CHARGE_OUT,
		ALIEN_PRAWN_HIT,
		ALIEN_PRAWN_HIT_02,
		ALIEN_PRAWN_HIT_LAUNCH,
		ALIEN_PRAWN_HIT_LAUNCH_FALLING,
		ALIEN_PRAWN_HIT_LAUNCH_FALLING_FAR,
		ALIEN_PRAWN_LAUNCH_FAR,
		ALIEN_PRAWN_LAUNCH_LAND,
		ALIEN_PRAWN_LOCK,
		ALIEN_PRAWN_MID,
		ALIEN_PRAWN_SPINN,
		ALIEN_PRAWN_IDLE,
		ALIEN_PRAWN_IDLE_CODEX,
		ALIEN_PRAWN_RUN,
		ALIEN_PRAWN_STUNNED_IN,
		ALIEN_PRAWN_STUNNED,
		ALIEN_PRAWN_END,
	};

	enum BATPOTATO_RIG_ANIM
	{
		BATPOTATO_RIG_ATTACK01,
		BATPOTATO_RIG_HIT,
		BATPOTATO_RIG_HIT_LAUNCH,
		BATPOTATO_RIG_HIT_LAUNCH_FALLING,
		BATPOTATO_RIG_HIT_LAUNCH_FALLING_FAR,
		BATPOTATO_RIG_HIT_LAUNCH_FAR,
		BATPOTATO_RIG_HIT_LAUNCH_LAND,
		BATPOTATO_RIG_IDLE,
		BATPOTATO_RIG_RUN,
		BATPOTATO_RIG_STUNNED,
		BATPOTATO_RIG_STUNNED_IN,
		BATPOTATO_RIG_END,
	};

	enum CANNON_SPIDER_ANIM
	{
		CANNON_SPIDER_AIM_LEFT,
		CANNON_SPIDER_IDLE,
		CANNON_SPIDER_AIM_RIGHT,
		CANNON_SPIDER_ATTACK01,
		CANNON_SPIDER_ATTACK02,
		CANNON_SPIDER_HIT,
		CANNON_SPIDER_HIT_LAUNCH,
		CANNON_SPIDER_HIT_LAUNCH_FALLING,
		CANNON_SPIDER_HIT_LAUNCH_FALLING_FAR,
		CANNON_SPIDER_HIT_LAUNCH_FAR,
		CANNON_SPIDER_HIT_LAUNCH_LAND,
		CANNON_SPIDER_RUN_F,
		CANNON_SPIDER_STUNNED,
		CANNON_SPIDER_STUNNED_IN,
		CANNON_SPIDER_TURN180_L,
		CANNON_SPIDER_TURN180_R,
		CANNON_SPIDER_TURN90_L,
		CANNON_SPIDER_TURN90_R,
		CANNON_SPIDER_ANIM_END
	};

	enum CRYSTAL_GOLEM_ANIM
	{
		CRYSTAL_GOLEM_APPEAR,
		CRYSTAL_GOLEM_ATTACK_AREA, // 75.f
		CRYSTAL_GOLEM_ATTACK_AREA_02, // 58.f
		CRYSTAL_GOLEM_ATTACK_RANGE,
		CRYSTAL_GOLEM_DEATH,
		CRYSTAL_GOLEM_EATTING_IN,
		CRYSTAL_GOLEM_EATTING_LOOP,
		CRYSTAL_GOLEM_EATTING_OUT,
		CRYSTAL_GOLEM_HIT,
		CRYSTAL_GOLEM_HIT_BODY,
		CRYSTAL_GOLEM_IDLE,  
		CRYSTAL_GOLEM_IDLE_CODEX,
		CRYSTAL_GOLEM_INTRO,
		CRYSTAL_GOLEM_STUNNED,
		CRYSTAL_GOLEM_STUNNED_IN,
		CRYSTAL_GOLEM_TURN180,
		CRYSTAL_GOLEM_WALK,
		CRYSTAL_GOLEM_WALK_OUT,
		CRYSTAL_GOLEM_ANIM_END
	};

	enum SPIDER_ANIM
	{
		SPIDER_ANIM_END,
	};

	enum QUEEN_MOGOS_ANIM
	{
		QUEEN_MOGOS_ANIM_END,
	};
}