#pragma once

namespace Client
{
	enum LEVELID { LEVEL_STATIC, LEVEL_IMGUI, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_LOADING, LEVEL_END };

	enum CLINT_ANIM
	{
		CLINT_SHOOT = 5,
		CLINT_DASH = 27,
		CLINT_IDLE = 64,
		CLINT_MVP = 74,
		CLINT_RUN = 89,
		CLINT_SKILL_01 = 109,
		CLINT_SKILL_02 = 112,
		CLINT_ULTIMATE01 = 133,
		CLINT_ULTIMATE02 = 135,
		CLINT_WALK_B = 142,
		CLINT_WALK_BL,
		CLINT_WALK_BL_45,
		CLINT_WALK_BR,
		CLINT_WALK_BR_45,
		CLINT_WALK_F,
		CLINT_WALK_FL,
		CLINT_WALK_FL_45,
		CLINT_WALK_FR,
		CLINT_WALK_FR_45,
		CLINT_WEAPONCHHANGE = 152,
	};

	enum ALIEN_PRAWN_ANIM
	{
		ALIEN_PRAWN_APPEAR,
		ALIEN_PRAWN_ATTACK01,
		ALIEN_PRAWN_ATTACK01_MID,
		ALIEN_PRAWN_ATTACK02,
		ALIEN_PRAWN_CHARGE,
		ALIEN_PRAWN_CHARGE_IN,
		ALIEN_PRAWN_CHARGE_OUT,
		ALIEN_PRAWN_HIT,
		ALIEN_PRAWN_HIT_02,
		ALIEN_PRAWN_HIT_LAUNCH,
		ALIEN_PRAWN_HIT_LAUNCH_FALLING,
		ALIEN_PRAWN_HIT_LAUNCH_FALLING_FAR,
		ALIEN_PRAWN_LAUNCH_FAR,
		ALIEN_PRAWN_LAUNCH_LAND,
		ALIEN_PRAWN_LOCK,
		ALIEN_PRAWN_MID,
		ALIEN_PRAWN_SPINN,
		ALIEN_PRAWN_IDLE,
		ALIEN_PRAWN_IDLE_CODEX,
		ALIEN_PRAWN_RUN,
		ALIEN_PRAWN_STUNNED_IN,
		ALIEN_PRAWN_STUNNED,
		ALIEN_PRAWN_END,
	};

	enum BATPOTATO_RIG_ANIM
	{
		BATPOTATO_RIG_ATTACK01,
		BATPOTATO_RIG_HIT,
		BATPOTATO_RIG_HIT_LAUNCH,
		BATPOTATO_RIG_HIT_LAUNCH_FALLING,
		BATPOTATO_RIG_HIT_LAUNCH_FALLING_FAR,
		BATPOTATO_RIG_HIT_LAUNCH_FAR,
		BATPOTATO_RIG_HIT_LAUNCH_LAND,
		BATPOTATO_RIG_IDLE,
		BATPOTATO_RIG_RUN,
		BATPOTATO_RIG_STUNNED,
		BATPOTATO_RIG_STUNNED_IN,
		BATPOTATO_RIG_END,
	};

	enum CANNON_SPIDER_ANIM
	{
		CANNON_SPIDER_AIM_LEFT,
		CANNON_SPIDER_IDLE,
		CANNON_SPIDER_AIM_RIGHT,
		CANNON_SPIDER_ATTACK01,
		CANNON_SPIDER_ATTACK02,
		CANNON_SPIDER_HIT,
		CANNON_SPIDER_HIT_LAUNCH,
		CANNON_SPIDER_HIT_LAUNCH_FALLING,
		CANNON_SPIDER_HIT_LAUNCH_FALLING_FAR,
		CANNON_SPIDER_HIT_LAUNCH_FAR,
		CANNON_SPIDER_HIT_LAUNCH_LAND,
		CANNON_SPIDER_RUN_F,
		CANNON_SPIDER_STUNNED,
		CANNON_SPIDER_STUNNED_IN,
		CANNON_SPIDER_TURN180_L,
		CANNON_SPIDER_TURN180_R,
		CANNON_SPIDER_TURN90_L,
		CANNON_SPIDER_TURN90_R,
		CANNON_SPIDER_ANIM_END
	};

	enum CRYSTAL_GOLEM_ANIM
	{
		CRYSTAL_GOLEM_APPEAR,
		CRYSTAL_GOLEM_ATTACK_AREA, // 75.f
		CRYSTAL_GOLEM_ATTACK_AREA_02, // 58.f
		CRYSTAL_GOLEM_ATTACK_RANGE,
		CRYSTAL_GOLEM_DEATH,
		CRYSTAL_GOLEM_EATTING_IN,
		CRYSTAL_GOLEM_EATTING_LOOP,
		CRYSTAL_GOLEM_EATTING_OUT,
		CRYSTAL_GOLEM_HIT,
		CRYSTAL_GOLEM_HIT_BODY,
		CRYSTAL_GOLEM_IDLE,  
		CRYSTAL_GOLEM_IDLE_CODEX,
		CRYSTAL_GOLEM_INTRO,
		CRYSTAL_GOLEM_STUNNED,
		CRYSTAL_GOLEM_STUNNED_IN,
		CRYSTAL_GOLEM_TURN180,
		CRYSTAL_GOLEM_WALK,
		CRYSTAL_GOLEM_WALK_OUT,
		CRYSTAL_GOLEM_ANIM_END
	};

	enum SPIDER_ANIM
	{
		SPIDER_APPEAR,
		SPIDER_APPEAR2,
		SPIDER_ATTACK,
		SPIDER_ATTACK_B,
		SPIDER_ATTACK_MID,
		SPIDER_CINEMATIC_01, // 쓰지마시오
		SPIDER_HIT,
		SPIDER_HIT_B,
		SPIDER_HIT_LAUNCH,
		SPIDER_HIT_LAUNCH_FALLING,
		SPIDER_HIT_LAUNCH_FAR,
		SPIDER_HIT_LAUNCH_FAR_FALLING,
		SPIDER_HIT_LAUNCH_FALLING_ROOTMOTIONLESS,
		SPIDER_HIT_LAUNCH_INPLACE,
		SPIDER_HIT_LAUNCH_LAND,
		SPIDER_HIT_MID,
		SPIDER_SPINN,
		SPIDER_SPINN_FALLING,
		SPIDER_SPINN_LOOP,
		SPIDER_IDLE,
		SPIDER_RUN_DEV,
		SPIDER_STUNNED,
		SPIDER_STUNNED_IN,
		SPIDER_SUMMON_SPIDERS,
		SPIDER_WALK,
		SPIDER_WALK_ELITE,
		SPIDER_ANIM_END,
	};

	enum QUEEN_MOGGOTH_ANIM
	{
		QUEEN_MOGGOTH_APPEAR,
		QUEEN_MOGGOTH_APPEAR2,
		QUEEN_MOGGOTH_CAPSULE_STEAL,
		QUEEN_MOGGOTH_EVENT_ATTACK,
		QUEEN_MOGGOTH_HAZARD01,
		QUEEN_MOGGOTH_HAZARD02,
		QUEEN_MOGGOTH_HIT_BODY,
		QUEEN_MOGGOTH_HIT_TAIL,
		QUEEN_MOGGOTH_P1_ATTACK01,  // Queen_Moggoth_P1_Attack01  78.0
		QUEEN_MOGGOTH_P1_ATTACK02, // Queen_Moggoth_P1_Attack02  102.0
		QUEEN_MOGGOTH_P1_ATTACK03, // Queen_Moggoth_P1_Attack03  163.0
		QUEEN_MOGGOTH_P1_ATTACK04_IN, // Queen_Moggoth_P1_Attack04_in  175.0    11
		QUEEN_MOGGOTH_P1_ATTACK04_LOOP, // Queen_Moggoth_P1_Attack04_loop  50.0
		QUEEN_MOGGOTH_P1_ATTACK04_OUT, // Queen_Moggoth_P1_Attack04_out  130.0
		QUEEN_MOGGOTH_P1_IDLE, //
		QUEEN_MOGGOTH_P1_TO_P2,
		QUEEN_MOGGOTH_P1_WALK_BACK,
		QUEEN_MOGGOTH_P1_WALK_FWD,
		QUEEN_MOGGOTH_P1_WALK_LEFT,
		QUEEN_MOGGOTH_P1_WALK_RIGHT,
		QUEEN_MOGGOTH_P2_ATTACK01, // Queen_Moggoth_P2_Attack01  100.0
		QUEEN_MOGGOTH_P2_ATTACK02_IN, // Queen_Moggoth_P2_Attack02_in 70.0
		QUEEN_MOGGOTH_P2_ATTACK02_LOOP, // Queen_Moggoth_P2_Attack02_loop 30.0
		QUEEN_MOGGOTH_P2_ATTACK02_OUT, // Queen_Moggoth_P2_Attack_out 70.0
		QUEEN_MOGGOTH_P2_ATTACK03, // Queen_Moggoth_P2_Attack03  95.0
		QUEEN_MOGGOTH_P2_ATTACK04_AIM_LEFT,  // 쓰지마시오
		QUEEN_MOGGOTH_P2_ATTACK04_LOOP,
		QUEEN_MOGGOTH_P2_ATTACK04_AIM_MIDDLE, // 쓰지마시오
		QUEEN_MOGGOTH_P2_ATTACK04_AIM_RIGHT, // 쓰지마시오
		QUEEN_MOGGOTH_P2_ATTACK04_IN, // Queen_Moggoth_P2_Attack04_in  45.0
		QUEEN_MOGGOTH_P2_ATTACK04_LOOP_RIGHT, // Queen_Moggoth_P2_Attack_loop_right  30.0
		QUEEN_MOGGOTH_P2_ATTACK04_OUT, // Queen_Moggoth_P2_Attack04_out 70.0
		QUEEN_MOGGOTH_P2_ATTACK04_SHOT, // Queen_Moggoth_P2_Attack04_shot  30.0
		QUEEN_MOGGOTH_P2_IDLE, // Queen_Moggoth_P2_Idle  70.0
		QUEEN_MOGGOTH_P2_TO_P3, // Queen_Moggoth_P2_to_P3  100.0
		QUEEN_MOGGOTH_P2_WALK_BACK, 
		QUEEN_MOGGOTH_P2_WALK_BL, 
		QUEEN_MOGGOTH_P2_WALK_BR,
		QUEEN_MOGGOTH_P2_WALK_FL,
		QUEEN_MOGGOTH_P2_WALK_FR,
		QUEEN_MOGGOTH_P2_WALK_FWD,
		QUEEN_MOGGOTH_P2_WALK_LEFT,
		QUEEN_MOGGOTH_P2_WALK_RIGHT,
		QUEEN_MOGGOTH_P3_DEATH,
		QUEEN_MOGGOTH_P3_IDLE,
		QUEEN_MOGGOTH_P3_JUMP, // Queen_Moggoth_P3_Jump  110.
		QUEEN_MOGGOTH_P3_TURN_LEFT_FAST,
		QUEEN_MOGGOTH_P3_TURN_LEFT_SLOW,
		QUEEN_MOGGOTH_P3_TURN_RIGHT_FAST,
		QUEEN_MOGGOTH_P3_TURN_RIGHT_SLOW,
		QUEEN_MOGGOTH_TEMPROOTMOTIONLESSLEFT,
		QUEEN_MOGGOTH_TEMPROOTMOTIONLESSRIGHT,
		QUEEN_MOGGOTH_ANIM_END,
	};
}